import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AiDisclaimer } from "@/components/AiDisclaimer";
import { toast } from "sonner";
import { generatePlan, type PlannerResult } from "@/lib/ai.functions";
import {
  CalendarRange,
  Plus,
  Trash2,
  Loader2,
  Wand2,
  Lightbulb,
  Download,
  Clock,
} from "lucide-react";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner — WorkSmart AI" },
      {
        name: "description",
        content: "Turn your task list into a prioritized daily or weekly schedule with AI.",
      },
      { property: "og:title", content: "AI Task Planner" },
      {
        property: "og:description",
        content: "Smart scheduling, time blocks, and productivity tips powered by AI.",
      },
    ],
  }),
  component: PlannerPage,
});

type Priority = "low" | "medium" | "high" | "urgent";
type Task = {
  id: string;
  name: string;
  description: string;
  priority: Priority;
  dueDate: string;
  duration: string;
};

function newTask(): Task {
  return {
    id: Math.random().toString(36).slice(2, 9),
    name: "",
    description: "",
    priority: "medium",
    dueDate: "",
    duration: "",
  };
}

const PRIORITY_STYLES: Record<Priority, string> = {
  low: "bg-muted text-muted-foreground",
  medium: "bg-primary/10 text-primary",
  high: "bg-warning/15 text-warning",
  urgent: "bg-accent/15 text-accent",
};

function PlannerPage() {
  const callPlan = useServerFn(generatePlan);
  const [tasks, setTasks] = useState<Task[]>([
    { ...newTask(), name: "Review Q4 roadmap", priority: "high", duration: "90m" },
    { ...newTask(), name: "Reply to client emails", priority: "medium", duration: "45m" },
    { ...newTask(), name: "1:1 with Maya", priority: "medium", duration: "30m" },
  ]);
  const [scheduleType, setScheduleType] = useState<"daily" | "weekly">("daily");
  const [workingHours, setWorkingHours] = useState("09:00 - 17:00");
  const [notes, setNotes] = useState("");
  const [plan, setPlan] = useState<PlannerResult | null>(null);

  const mutation = useMutation({
    mutationFn: async () =>
      (await callPlan({
        data: {
          tasks: tasks
            .filter((t) => t.name.trim())
            .map(({ id: _id, ...rest }) => rest),
          scheduleType,
          workingHours,
          notes,
        },
      })) as PlannerResult,
    onSuccess: (data) => {
      setPlan(data);
      toast.success("Schedule generated");
    },
    onError: (e: unknown) => {
      toast.error(e instanceof Error ? e.message : "Failed to generate schedule");
    },
  });

  const exportPlan = () => {
    if (!plan) return;
    const lines = [
      `${scheduleType === "weekly" ? "Weekly" : "Daily"} schedule — generated by WorkSmart AI`,
      "",
      plan.summary,
      "",
      ...plan.blocks.map(
        (b) =>
          `${b.day ? b.day + " · " : ""}${b.start}-${b.end}  ${b.task}  [${b.priority}]${b.note ? "  — " + b.note : ""}`,
      ),
      "",
      "Insights:",
      ...plan.insights.map((i) => "• " + i),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `worksmart-${scheduleType}-schedule.txt`;
    a.click();
  };

  return (
    <div className="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
      <header className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-gradient-secondary text-accent-foreground shadow-elegant">
            <CalendarRange className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <h1 className="truncate font-display text-2xl font-bold sm:text-3xl">AI Task Planner</h1>
            <p className="text-sm text-muted-foreground">
              Drop in your tasks, get a prioritized schedule with time blocks.
            </p>
          </div>
        </div>
      </header>

      <div className="grid gap-6 lg:grid-cols-[1fr_1.2fr]">
        {/* Input */}
        <Card className="border-border/60 p-5 shadow-sm sm:p-6">
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label>Schedule type</Label>
              <Tabs value={scheduleType} onValueChange={(v) => setScheduleType(v as "daily" | "weekly")}>
                <TabsList className="grid w-full grid-cols-2 bg-muted/40">
                  <TabsTrigger value="daily">Daily</TabsTrigger>
                  <TabsTrigger value="weekly">Weekly</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="wh">Working hours</Label>
              <Input id="wh" value={workingHours} onChange={(e) => setWorkingHours(e.target.value)} />
            </div>
          </div>

          <div className="mt-5">
            <div className="mb-2 flex items-center justify-between">
              <Label>Tasks</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => setTasks([...tasks, newTask()])}
              >
                <Plus className="h-3.5 w-3.5" /> Add task
              </Button>
            </div>
            <div className="space-y-2">
              {tasks.map((t, idx) => (
                <div
                  key={t.id}
                  className="space-y-2 rounded-xl border border-border/60 bg-muted/30 p-3"
                >
                  <div className="flex items-start gap-2">
                    <Input
                      placeholder={`Task ${idx + 1} name`}
                      value={t.name}
                      onChange={(e) =>
                        setTasks(tasks.map((x) => (x.id === t.id ? { ...x, name: e.target.value } : x)))
                      }
                      className="bg-background"
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => setTasks(tasks.filter((x) => x.id !== t.id))}
                      disabled={tasks.length === 1}
                      aria-label="Remove task"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                  <div className="grid gap-2 sm:grid-cols-3">
                    <Select
                      value={t.priority}
                      onValueChange={(v) =>
                        setTasks(tasks.map((x) => (x.id === t.id ? { ...x, priority: v as Priority } : x)))
                      }
                    >
                      <SelectTrigger className="bg-background"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="low">Low priority</SelectItem>
                        <SelectItem value="medium">Medium priority</SelectItem>
                        <SelectItem value="high">High priority</SelectItem>
                        <SelectItem value="urgent">Urgent</SelectItem>
                      </SelectContent>
                    </Select>
                    <Input
                      placeholder="Duration e.g. 45m"
                      value={t.duration}
                      onChange={(e) =>
                        setTasks(tasks.map((x) => (x.id === t.id ? { ...x, duration: e.target.value } : x)))
                      }
                      className="bg-background"
                    />
                    <Input
                      placeholder="Due (optional)"
                      value={t.dueDate}
                      onChange={(e) =>
                        setTasks(tasks.map((x) => (x.id === t.id ? { ...x, dueDate: e.target.value } : x)))
                      }
                      className="bg-background"
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-4 space-y-1.5">
            <Label htmlFor="notes">Notes for the planner</Label>
            <Textarea
              id="notes"
              rows={3}
              placeholder="Lunch at 12:30, no meetings before 10:00…"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
            />
          </div>

          <Button
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending || !tasks.some((t) => t.name.trim())}
            size="lg"
            className="mt-5 w-full bg-gradient-primary text-primary-foreground shadow-elegant"
          >
            {mutation.isPending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> Generating…
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4" /> Generate schedule
              </>
            )}
          </Button>
        </Card>

        {/* Output */}
        <div className="space-y-4">
          <Card className="min-h-[420px] border-border/60 p-5 shadow-sm sm:p-6">
            {!plan && !mutation.isPending && (
              <div className="flex h-full min-h-[380px] flex-col items-center justify-center text-center text-muted-foreground">
                <div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-secondary text-accent-foreground shadow-glow">
                  <CalendarRange className="h-6 w-6" />
                </div>
                <p className="mt-4 font-display text-base font-semibold text-foreground">
                  Your AI schedule will appear here
                </p>
                <p className="mt-1 max-w-xs text-sm">
                  Add tasks and click Generate — WorkSmart will order them by priority and slot them into
                  your working hours.
                </p>
              </div>
            )}

            {mutation.isPending && (
              <div className="space-y-3">
                <div className="h-5 w-1/2 animate-pulse rounded bg-muted" />
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="h-12 animate-pulse rounded-xl bg-muted/70" />
                ))}
              </div>
            )}

            {plan && !mutation.isPending && (
              <div className="space-y-4">
                <div className="rounded-xl bg-gradient-surface p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Summary
                  </p>
                  <p className="mt-1 text-sm leading-relaxed">{plan.summary}</p>
                </div>

                <div className="space-y-2">
                  {plan.blocks.map((b, i) => (
                    <div
                      key={i}
                      className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-border/60 bg-card p-3"
                    >
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <Clock className="h-3.5 w-3.5" />
                        <div className="font-mono">
                          {b.day && <span className="mr-1.5 text-primary font-semibold">{b.day.slice(0, 3)}</span>}
                          {b.start}–{b.end}
                        </div>
                      </div>
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium">{b.task}</p>
                        {b.note && <p className="truncate text-[11px] text-muted-foreground">{b.note}</p>}
                      </div>
                      <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ${PRIORITY_STYLES[b.priority]}`}>
                        {b.priority}
                      </span>
                    </div>
                  ))}
                </div>

                {plan.insights.length > 0 && (
                  <div className="rounded-xl border border-warning/30 bg-warning/5 p-4">
                    <div className="mb-2 flex items-center gap-2 text-sm font-semibold">
                      <Lightbulb className="h-4 w-4 text-warning" /> Productivity insights
                    </div>
                    <ul className="space-y-1.5 text-sm">
                      {plan.insights.map((tip, i) => (
                        <li key={i} className="flex gap-2">
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-warning" />
                          <span>{tip}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="flex flex-wrap gap-2">
                  <Button size="sm" variant="outline" onClick={exportPlan}>
                    <Download className="h-3.5 w-3.5" /> Export schedule
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => mutation.mutate()}
                  >
                    <Wand2 className="h-3.5 w-3.5" /> Regenerate
                  </Button>
                </div>
              </div>
            )}
          </Card>

          <AiDisclaimer />
        </div>
      </div>
    </div>
  );
}
